'use strict';
const $=s=>document.querySelector(s), root=$('#blocks');let loaded=false,activeBlock=null,savedRange=null,dirty=false,history=[],future=[],lastSaved='',activeChildId=null;
const send=body=>window.webkit?.messageHandlers.page.postMessage(JSON.stringify(body));
const uid=()=>crypto.randomUUID();
const empty=()=>({Id:uid(),Kind:'text',Runs:[],Cells:[],Boxed:false});
function runsFrom(el){const out=[];function walk(node,style){if(node.nodeType===3){if(node.data)out.push({Text:node.data,Bold:style.bold,Italic:style.italic,Boxed:style.box,Size:style.size});return;}if(node.nodeType!==1)return;const tag=node.tagName;let next={...style};if(['B','STRONG'].includes(tag)||node.style.fontWeight==='bold')next.bold=true;if(['I','EM'].includes(tag)||node.style.fontStyle==='italic')next.italic=true;if(node.classList.contains('inline-box'))next.box=true;if(node.style.fontSize)next.size=Math.max(10,Math.min(96,parseFloat(node.style.fontSize)||18));if(tag==='BR'){out.push({Text:'\n',Bold:next.bold,Italic:next.italic,Boxed:next.box,Size:next.size});return;}if(['DIV','P'].includes(tag)&&out.length&&!out.at(-1).Text.endsWith('\n'))out.push({Text:'\n',Bold:false,Italic:false,Boxed:false,Size:next.size});for(const child of node.childNodes)walk(child,next);}
for(const n of el.childNodes)walk(n,{bold:false,italic:false,box:false,size:18});return out;}
function putRuns(el,runs){for(const r of runs||[]){const s=document.createElement('span');s.textContent=r.Text;s.style.fontSize=r.Size+'px';if(r.Bold)s.style.fontWeight='bold';if(r.Italic)s.style.fontStyle='italic';if(r.Boxed)s.className='inline-box';el.append(s);}}
function snapshot(){return {Title:window.pageTitle||'',Blocks:[...root.children].map(el=>({Id:el.dataset.id,Kind:el.dataset.kind,Boxed:el.classList.contains('boxed'),FileName:el.dataset.file||null,ImageWidth:el.dataset.kind==='image'?(parseFloat(el.querySelector('.image-size').style.width)||0):0,Runs:el.dataset.kind==='text'?runsFrom(el.querySelector('.editable')):[],CellColors:el.dataset.kind==='table'?tableColors(el.querySelector('table')):{},ColumnWidths:el.dataset.kind==='table'?tableWidths(el.querySelector('table')):[],RowHeights:el.dataset.kind==='table'?[...el.querySelectorAll('tr')].map(r=>parseFloat(r.style.height)||54):[],Cells:el.dataset.kind==='table'?[...el.querySelectorAll('tr')].map(row=>[...row.cells].map(c=>runsFrom(c.querySelector('.editable')))):[]}))};}
function mark(){if(!loaded)return;dirty=true;const text=JSON.stringify(snapshot());if(text!==lastSaved){send({action:'save',text});$('#status').textContent='saving…';}}
window.pageSnapshot=()=>loaded?JSON.stringify(snapshot()):null;
window.pageSaveStatus=(ok,message)=>{dirty=!ok;if(ok)lastSaved=JSON.stringify(snapshot());$('#status').hidden=ok;$('#status').textContent=ok?'':message;$('#status').classList.toggle('error',!ok);};
function remember(){if(!loaded)return;const s=JSON.stringify(snapshot());if(history.at(-1)!==s){history.push(s);if(history.length>100)history.shift();}future=[];}
function editable(runs=[]){const e=document.createElement('div');e.className='editable';e.contentEditable='true';e.setAttribute('aria-label','Page text');putRuns(e,runs);e.addEventListener('beforeinput',ev=>{if(ev.inputType==='historyUndo'||ev.inputType==='historyRedo'){ev.preventDefault();undo(ev.inputType==='historyRedo');}else remember();});return e;}
function block(b){const el=document.createElement('section');el.className='block'+(b.Boxed?' boxed':'');el.dataset.id=b.Id;el.dataset.kind=b.Kind;const grip=document.createElement('button');grip.textContent='⋮⋮';grip.className='grip';grip.draggable=true;grip.setAttribute('aria-label','Drag block to reorder');grip.addEventListener('dragstart',e=>{e.dataTransfer.setData('application/x-miche-block',b.Id);e.dataTransfer.effectAllowed='move';});el.append(grip);
if(b.Kind==='text')el.append(editable(b.Runs));
if(b.Kind==='image'){el.dataset.file=b.FileName;const size=document.createElement('div');size.className='image-size';if(b.ImageWidth>0)size.style.width=b.ImageWidth+'px';size.addEventListener('pointerup',()=>mark());const img=document.createElement('img');img.className='image';img.alt='Page image';img.src=(window.pageImages||{})[b.FileName]||'';size.append(img);el.append(size);}
if(b.Kind==='table'){const t=document.createElement('table');for(const row of b.Cells){const tr=t.insertRow();for(const cell of row)tr.insertCell().append(editable(cell));}enhanceTable(t,b);el.append(t);}
el.addEventListener('pointerdown',()=>activeBlock=el);el.addEventListener('contextmenu',e=>{e.preventDefault();activeBlock=el;capture();$('#format').hidden=true;$('#addRow').hidden=$('#addColumn').hidden=b.Kind!=='table';showMenu($('#context'),e.clientX,e.clientY);});return el;}
function render(doc){root.replaceChildren(...doc.Blocks.map(block));if(!root.children.length)root.append(block(empty()));}
window.pageLoad=(doc,images,children)=>{window.pageTitle=doc.Title||'';window.pageImages=images||{};render(doc);window.pageChildren(children||[]);loaded=true;lastSaved=JSON.stringify(snapshot());root.querySelector('.editable')?.focus();};
window.pageChildren=items=>{$('#children').replaceChildren();for(const p of items){const b=document.createElement('button');b.className='child';b.textContent=p.Title||'untitled page';const hint=document.createElement('small');hint.textContent='open ↗';b.append(hint);b.onclick=()=>send({action:'openPage',id:p.Id});b.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();activeChildId=p.Id;$('#context').hidden=$('#addMenu').hidden=$('#format').hidden=true;showMenu($('#childMenu'),e.clientX,e.clientY);};$('#children').append(b);}};
window.pageSetTitle=title=>{window.pageTitle=title;mark();};
window.pageInsertImage=(name,data)=>{remember();window.pageImages[name]=data;const el=block({Id:uid(),Kind:'image',FileName:name,Runs:[],Cells:[],Boxed:false});insert(el);mark();};
function insert(el){if(activeBlock?.isConnected)activeBlock.after(el);else root.append(el);activeBlock=el;el.querySelector('.editable')?.focus();el.scrollIntoView({block:'nearest'});}
function capture(){const s=getSelection();if(s.rangeCount){const r=s.getRangeAt(0);if(root.contains(r.commonAncestorContainer)){savedRange=r.cloneRange();return;}}savedRange=null;}
function restore(){if(savedRange){const s=getSelection();s.removeAllRanges();s.addRange(savedRange);}}
function showMenu(menu,x,y){menu.hidden=false;menu.style.left=Math.max(5,Math.min(x,innerWidth-menu.offsetWidth-5))+'px';menu.style.top=Math.max(5,Math.min(y,innerHeight-menu.offsetHeight-5))+'px';}
function format(action){restore();const s=getSelection();if(!s.rangeCount||s.isCollapsed)return;const r=s.getRangeAt(0),start=(r.startContainer.nodeType===1?r.startContainer:r.startContainer.parentElement)?.closest('.editable'),end=(r.endContainer.nodeType===1?r.endContainer:r.endContainer.parentElement)?.closest('.editable');if(!start||start!==end){$('#status').textContent='Select text within one paragraph or cell.';return;}remember();if(action==='bold'||action==='italic')document.execCommand(action);else{const fragment=r.cloneContents(),span=document.createElement('span');span.append(fragment);if(action==='box')span.className='inline-box';else{const walker=document.createTreeWalker(start,NodeFilter.SHOW_TEXT);let first;while(walker.nextNode()){const node=walker.currentNode,part=document.createRange();part.selectNodeContents(node);if(r.comparePoint(node,0)<0)part.setStart(r.startContainer,r.startOffset);if(r.comparePoint(node,node.data.length)>0)part.setEnd(r.endContainer,r.endOffset);if(part.toString().length){first=node.parentElement;break;}}const current=parseFloat(getComputedStyle(first||start).fontSize)||18;span.style.fontSize=Math.max(10,Math.min(96,current*(action==='bigger'?1.1:1/1.1)))+'px';// Existing run sizes must not mask the selected new size.
for(const child of span.querySelectorAll('[style]'))child.style.fontSize='';}const token=uid();span.dataset.formatId=token;document.execCommand('insertHTML',false,span.outerHTML);const inserted=start.querySelector('[data-format-id="'+token+'"]');if(inserted){const selection=getSelection(),range=document.createRange();range.selectNodeContents(inserted);selection.removeAllRanges();selection.addRange(range);inserted.removeAttribute('data-format-id');}}capture();mark();}
function undo(redo=false){const source=redo?future:history,target=redo?history:future;if(!source.length)return;target.push(JSON.stringify(snapshot()));render(JSON.parse(source.pop()));activeBlock=null;savedRange=null;$('#format').hidden=true;mark();}
for(const b of document.querySelectorAll('[data-format]')){b.onmousedown=e=>e.preventDefault();b.onclick=()=>{format(b.dataset.format);$('#context').hidden=true;};}
$('#boxBlock').onclick=()=>{if(activeBlock){remember();activeBlock.classList.toggle('boxed');mark();}$('#context').hidden=true;};
$('#removeBlock').onclick=()=>{if(activeBlock){remember();activeBlock.remove();if(!root.children.length)root.append(block(empty()));activeBlock=null;mark();}$('#context').hidden=true;};
$('#addRow').onclick=()=>{const t=activeBlock?.querySelector('table');if(t&&t.rows.length<50){remember();const row=t.insertRow();for(let i=0;i<t.rows[0].cells.length;i++)row.insertCell().append(editable());mark();}$('#context').hidden=true;};
$('#addColumn').onclick=()=>{const t=activeBlock?.querySelector('table');if(t&&t.rows[0].cells.length<12){remember();for(const row of t.rows)row.insertCell().append(editable());mark();}$('#context').hidden=true;};

function addContent(kind){$('#addMenu').hidden=true;if(kind==='image'){send({action:'pickImage'});return;}if(kind==='page'){send({action:'newPage'});return;}remember();insert(block(kind==='table'?{Id:uid(),Kind:'table',Runs:[],Cells:Array.from({length:3},()=>Array.from({length:3},()=>[])),Boxed:false}:empty()));mark();}
for(const b of document.querySelectorAll('[data-add]'))b.onclick=()=>addContent(b.dataset.add);
for(const [label,kind] of [['Add text below','text'],['Add image…','image'],['Add table below','table'],['Add little page inside','page']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{$('#context').hidden=true;addContent(kind);};$('#context').append(b);}
root.addEventListener('input',mark);
document.addEventListener('selectionchange',()=>{if(!loaded)return;capture();const s=getSelection();if(s.isCollapsed||!savedRange){$('#format').hidden=true;return;}const r=savedRange.getBoundingClientRect();showMenu($('#format'),r.left,Math.max(5,r.top-42));});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.menu')&&!e.target.closest('#add')){$('#context').hidden=true;$('#addMenu').hidden=true;$('#childMenu').hidden=true;}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#context').hidden=$('#addMenu').hidden=$('#format').hidden=$('#childMenu').hidden=true;return;}if(!e.metaKey&&!e.ctrlKey)return;const key=e.key.toLowerCase();if(key==='q'){e.preventDefault();send({action:'quit'});return;}if(key==='b'||key==='i'){e.preventDefault();capture();format(key==='b'?'bold':'italic');}if(e.shiftKey&&(e.code==='Period'||e.code==='Comma')){e.preventDefault();capture();format(e.code==='Period'?'bigger':'smaller');}if(key==='z'){e.preventDefault();undo(e.shiftKey);}if(key==='s'){e.preventDefault();mark();}});
function imageFile(file){if(file.size>10000000||!['image/png','image/jpeg'].includes(file.type)){$('#status').textContent='Choose a PNG or JPEG under 10 MB.';return;}const reader=new FileReader();reader.onload=()=>send({action:'image',data:reader.result.split(',')[1]});reader.readAsDataURL(file);}
root.addEventListener('paste',e=>{e.preventDefault();const files=[...e.clipboardData.files];if(files.length){files.slice(0,10).forEach(imageFile);return;}remember();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'));mark();});
root.addEventListener('dragover',e=>e.preventDefault());root.addEventListener('drop',e=>{e.preventDefault();const id=e.dataTransfer.getData('application/x-miche-block');const target=e.target.closest('.block');if(id){const moving=[...root.children].find(n=>n.dataset.id===id);if(moving&&moving!==target){remember();if(target)target.after(moving);else root.append(moving);mark();}}else[...e.dataTransfer.files].slice(0,10).forEach(imageFile);});

// The same table schema and palette are used by Vision and /table widgets.
const palette=[['Ink','#302638'],['Rose','#573B4B'],['Lavender','#45405D'],['Sage','#354A43'],['Sand','#514735'],['Sky','#344753']];
let cellSelection=new Set(),cellAnchor=null,contextCell=null;
function tableColors(t){const colors={};for(const row of t.rows)for(const cell of row.cells)if(cell.dataset.color)colors[row.rowIndex+':'+cell.cellIndex]=cell.dataset.color;return colors;}
function tableWidths(t){return [...t.querySelectorAll('col')].map(c=>parseFloat(c.style.width)||120);}
function selectCell(cell,e){const t=cell.closest('table');if(!e.shiftKey&&!e.metaKey&&!e.ctrlKey){if(!cellSelection.has(cell)){cellSelection=new Set([cell]);cellAnchor=cell;}}else{e.preventDefault();if(e.shiftKey&&cellAnchor?.closest('table')===t){cellSelection.clear();for(const row of [...t.rows].slice(Math.min(cell.parentElement.rowIndex,cellAnchor.parentElement.rowIndex),Math.max(cell.parentElement.rowIndex,cellAnchor.parentElement.rowIndex)+1))for(const c of [...row.cells].slice(Math.min(cell.cellIndex,cellAnchor.cellIndex),Math.max(cell.cellIndex,cellAnchor.cellIndex)+1))cellSelection.add(c);}else{if(cellSelection.has(cell))cellSelection.delete(cell);else cellSelection.add(cell);cellAnchor=cell;}}
 document.querySelectorAll('td.selected').forEach(c=>c.classList.remove('selected'));for(const c of cellSelection)c.classList.add('selected');}
function enhanceTable(t,b){const cols=document.createElement('colgroup');for(let i=0;i<t.rows[0].cells.length;i++){const col=document.createElement('col');col.style.width=(b.ColumnWidths?.[i]||120)+'px';cols.append(col);}t.prepend(cols);t.style.tableLayout='fixed';
for(const row of t.rows){row.style.height=(b.RowHeights?.[row.rowIndex]||54)+'px';for(const cell of row.cells){const color=b.CellColors?.[row.rowIndex+':'+cell.cellIndex];if(color){cell.dataset.color=color;cell.style.background=color;}cell.addEventListener('pointerdown',e=>selectCell(cell,e));cell.addEventListener('contextmenu',()=>{contextCell=cell;if(!cellSelection.has(cell)){cellSelection=new Set([cell]);cellAnchor=cell;cell.classList.add('selected');}$('#tableOptions').hidden=false;});for(const rows of [false,true]){const grip=document.createElement('span');grip.className=rows?'row-grip':'col-grip';cell.append(grip);grip.onpointerdown=e=>{e.preventDefault();e.stopPropagation();if(!cellSelection.has(cell)){cellSelection=new Set([cell]);cellAnchor=cell;}remember();const indices=[...new Set([...cellSelection].filter(c=>c.closest('table')===t).map(c=>rows?c.parentElement.rowIndex:c.cellIndex))];const start=rows?e.clientY:e.clientX,initial=rows?parseFloat(row.style.height):parseFloat(cols.children[cell.cellIndex].style.width);grip.setPointerCapture(e.pointerId);grip.onpointermove=move=>{const value=Math.max(rows?28:40,Math.min(1000,initial+(rows?move.clientY:move.clientX)-start));for(const i of indices)(rows?t.rows[i]:cols.children[i]).style[rows?'height':'width']=value+'px';};grip.onpointerup=up=>{grip.onpointermove=null;grip.onpointerup=null;grip.releasePointerCapture(up.pointerId);mark();};};}}}
t.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const cell=e.target.closest('td');if(!cell)return;e.preventDefault();const all=[...t.querySelectorAll('td')],index=all.indexOf(cell)+(e.shiftKey?-1:1);if(index<0)return;if(index>=all.length){if(t.rows.length>=50)return;remember();const doc=snapshot(),b=doc.Blocks.find(b=>b.Id===t.closest('.block').dataset.id);b.Cells.push(Array.from({length:b.Cells[0].length},()=>[]));b.RowHeights.push(54);render(doc);mark();const replacement=[...root.querySelectorAll('.block')].find(el=>el.dataset.id===b.Id);replacement.querySelectorAll('td')[index]?.querySelector('.editable').focus();}else all[index].querySelector('.editable').focus();});}
function tableEdit(action){if(!contextCell?.isConnected)return;const t=contextCell.closest('table'),doc=snapshot(),block=doc.Blocks.find(b=>b.Id===t.closest('.block').dataset.id);const rows=[...new Set([...cellSelection].filter(c=>c.closest('table')===t).map(c=>c.parentElement.rowIndex))].sort((a,b)=>b-a),columns=[...new Set([...cellSelection].filter(c=>c.closest('table')===t).map(c=>c.cellIndex))].sort((a,b)=>b-a);remember();
let axis=null,index=-1,remove=false;
if(action==='deleteRows'&&rows.length<block.Cells.length){for(const r of rows){block.Cells.splice(r,1);block.RowHeights.splice(r,1);}remapColors(block,rows,true,true);}
if(action==='deleteColumns'&&columns.length<block.Cells[0].length){for(const c of columns){for(const row of block.Cells)row.splice(c,1);block.ColumnWidths.splice(c,1);}remapColors(block,columns,false,true);}
if(action==='rowBefore'||action==='rowAfter'){axis=true;index=contextCell.parentElement.rowIndex+(action==='rowAfter'?1:0);if(block.Cells.length>=50)return;block.Cells.splice(index,0,Array.from({length:block.Cells[0].length},()=>[]));block.RowHeights.splice(index,0,54);}
if(action==='colBefore'||action==='colAfter'){axis=false;index=contextCell.cellIndex+(action==='colAfter'?1:0);if(block.Cells[0].length>=12)return;for(const row of block.Cells)row.splice(index,0,[]);block.ColumnWidths.splice(index,0,120);}
if(axis!==null)remapColors(block,[index],axis,false);
if(action==='equalColumns')for(const c of columns)block.ColumnWidths[c]=block.ColumnWidths[contextCell.cellIndex];if(action==='equalRows')for(const r of rows)block.RowHeights[r]=block.RowHeights[contextCell.parentElement.rowIndex];
if(action.startsWith('color:'))for(const cell of cellSelection)if(cell.closest('table')===t)block.CellColors[cell.parentElement.rowIndex+':'+cell.cellIndex]=action.slice(6);
render(doc);cellSelection.clear();contextCell=null;$('#context').hidden=true;mark();}
function remapColors(block,indices,rows,remove){let next={};for(const [key,color] of Object.entries(block.CellColors)){let [r,c]=key.split(':').map(Number),v=rows?r:c;if(remove&&indices.includes(v))continue;const shift=indices.filter(i=>remove?i<v:i<=v).length;if(rows)r+=remove?-shift:shift;else c+=remove?-shift:shift;next[r+':'+c]=color;}block.CellColors=next;}
for(const [label,action] of [['Row above','rowBefore'],['Row below','rowAfter'],['Column left','colBefore'],['Column right','colAfter'],['Delete selected rows','deleteRows'],['Delete selected columns','deleteColumns'],['Equal column widths','equalColumns'],['Equal row heights','equalRows'],...palette.map(([name,color])=>['Color · '+name,'color:'+color])]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>tableEdit(action);$('#tableOptions').append(b);}
// Table-specific actions supersede the initial append buttons.
$('#addRow').hidden=$('#addColumn').hidden=true;
root.addEventListener('contextmenu',e=>{$('#addRow').hidden=$('#addColumn').hidden=true;$('#tableOptions').hidden=!e.target.closest('td');});

document.addEventListener('contextmenu',e=>{if(e.target.closest('.block'))return;e.preventDefault();$('#context').hidden=true;$('#format').hidden=true;activeBlock=null;showMenu($('#addMenu'),e.clientX,e.clientY);});
$('#deleteChild').onclick=()=>{if(activeChildId)send({action:'deleteChildPage',id:activeChildId});$('#childMenu').hidden=true;};
send({action:'ready'});
